global using API.Controllers;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.Extensions.Hosting;
global using Newtonsoft.Json;
global using System.Net;
global using System.Net.Http;
global using System.Text;
global using Xunit;
